### ISSUE TITLE
Helpers option

### ISSUE THREAD

**Issue by jamielob** [jazzdragon/reactive-var-helper#2]
Hi @jazzdragon!

Great simple plugin that I love using.  I'm not sure if this is something you're interested in adding to the plugin but I found myself adding template helpers over and over again that simply returned the reactive var.   I've modified the plugin for myself that does this by simply adding a `true` flag at the end of the list of variables.

For example: 

```
Template.signIn.reactiveVars({
    'signingIn': false
});

Template.signIn.reactiveVars({
    'name': 'Bozo',
        'version': 1.0.5
}, true);
```

The above code adds template helpers for `{{name}}` and `{{version}}` automatically, but not for `signingIn`.

Let me know if you want me to create a pull request or not.

Jamie

**Comment by alondahari** [comment]
Hi Jamie,
Great idea, I'd love a pull request!
How about we implement it a bit different though, like so:

``` javascript
Template.signIn.reactiveVars({
    'name': 'Bozo',
    withTemplateHelper: {
        'version': '1.0.5'
    }
});
```

so the name is without a helper.

**Comment by jamielob** [comment]
Looks good to me. PR generated!

**Comment by jamielob** [comment]
@jazzdragon - Let me know how it looks to you.

**Comment by alondahari** [comment]
Looks great. I added a comment on the PR.

**Comment by jamielob** [comment]
@jazzdragon - Oops. Mistake rectified!

**Comment by alondahari** [comment]
Great thanks!

**Comment by jazzdragon** [comment]
#3

**Comment by alondahari** [comment]
#3

**Comment by jamielob** [comment]
@jazzdragon : Great! Let me know when you've had a chance to up the version number and push to Atmosphere.

**Comment by alondahari** [comment]
Done and done :)

**Comment by jamielob** [comment]
@jazzdragon :+1:
